"""add active and admin flags to users

Revision ID: ecc9793b2c12
Revises: 1de429a3e27a
Create Date: 2026-03-16 22:25:39.777822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc9793b2c12'
down_revision: Union[str, Sequence[str], None] = '1de429a3e27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users ', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users ', sa.Column('id_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users ', 'id_admin')
    op.drop_column('users ', 'is_active')
    # ### end Alembic commands ###
